### ISSUE TITLE
ToDo MoBspatial development

### ISSUE THREAD

**Issue by FelixMay** [MoBiodiv/MoBspatial#1]
[x] Finish diversity-area relationship

**Comment by FelixMay** [comment]
- [ ] Add function that estimates negative binomial k at different scales
- [ ] Change options in simulation functions so that the number of cluster can be specified (simulate species ranges) @

**Comment by FelixMay** [comment]
- [] Type checking for S.pool and N.local
- [] Rename N.local to N
- [] better explain sigma in help and include species-specific sigma (similar to mother.points and cluster.points)

**Comment by KatharinaGerstner** [comment]
[] Improve error messages, e.g. if S.pool = 0

**Comment by FelixMay** [comment]
- [ ] Plottting functions for patterns
- [ ] Revise documentation
- [ ] Adapt vignettes
- [ ] Check CRAN release

**Comment by dmcglinn** [comment]
- [ ] Provide link in `README.md` to published paper in MEE.
